"""empty message

Revision ID: aef509a52410
Revises: c1ffa0b2f3c1
Create Date: 2026-05-09 19:34:56.030604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aef509a52410'
down_revision: Union[str, Sequence[str], None] = 'c1ffa0b2f3c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compras', sa.Column('valor_imposto', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('compras', 'valor_imposto')
    # ### end Alembic commands ###
