"""empty message

Revision ID: c1ffa0b2f3c1
Revises: c3f92db8005d
Create Date: 2026-05-09 15:17:32.654447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1ffa0b2f3c1'
down_revision: Union[str, Sequence[str], None] = 'c3f92db8005d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendas', sa.Column('venda_direta', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendas', 'venda_direta')
    # ### end Alembic commands ###
