"""empty message

Revision ID: c3f92db8005d
Revises: 4963e239fc90
Create Date: 2026-05-09 15:12:18.520233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3f92db8005d'
down_revision: Union[str, Sequence[str], None] = '4963e239fc90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compras', sa.Column('para_estoque', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('compras', 'para_estoque')
    # ### end Alembic commands ###
